# Generated by Django 3.1.3 on 2021-01-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
